name: 'foodmythbuster'
version: '1.0.0'
config-version: 2

profile: 'foodmythbuster'

model-paths: ["models"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  foodmythbuster:
    staging:
      +materialized: table
    marts:
      +materialized: table

seeds:
  foodmythbuster:
    health_claims:
      +column_types:
        claim_tag: STRING
        claim_family: STRING
