-- Tile 3: Healthy Junk by Category Group
-- Looker Studio Custom Query data source
-- Replace YOUR_PROJECT with your GCP project ID

WITH mapping AS (
  SELECT tag, grp FROM UNNEST([
    STRUCT('milks' AS tag, 'Milks & Dairy Drinks' AS grp),
    STRUCT('flavoured-milks', 'Milks & Dairy Drinks'),
    STRUCT('chocolate-milks', 'Milks & Dairy Drinks'),
    STRUCT('dairy-drinks', 'Milks & Dairy Drinks'),
    STRUCT('milk-drinks', 'Milks & Dairy Drinks'),
    STRUCT('condensed-milks', 'Milks & Dairy Drinks'),
    STRUCT('plant-based-milks', 'Milks & Dairy Drinks'),
    STRUCT('yogurts', 'Fermented Dairy'),
    STRUCT('fermented-milk-products', 'Fermented Dairy'),
    STRUCT('fermented-dairy-desserts', 'Fermented Dairy'),
    STRUCT('kefir', 'Fermented Dairy'),
    STRUCT('skyr', 'Fermented Dairy'),
    STRUCT('drinkable-yogurts', 'Fermented Dairy'),
    STRUCT('cheeses', 'Cheeses'),
    STRUCT('processed-cheeses', 'Cheeses'),
    STRUCT('cream-cheeses', 'Cheeses'),
    STRUCT('desserts', 'Desserts & Ice Cream'),
    STRUCT('dairy-desserts', 'Desserts & Ice Cream'),
    STRUCT('puddings', 'Desserts & Ice Cream'),
    STRUCT('frozen-desserts', 'Desserts & Ice Cream'),
    STRUCT('ice-creams-and-sorbets', 'Desserts & Ice Cream'),
    STRUCT('chilled-desserts', 'Desserts & Ice Cream'),
    STRUCT('custards', 'Desserts & Ice Cream'),
    STRUCT('ice-creams', 'Desserts & Ice Cream'),
    STRUCT('sorbets', 'Desserts & Ice Cream'),
    STRUCT('breakfast-cereals', 'Breakfast Cereals'),
    STRUCT('mueslis', 'Breakfast Cereals'),
    STRUCT('granolas', 'Breakfast Cereals'),
    STRUCT('corn-flakes', 'Breakfast Cereals'),
    STRUCT('chocolate-breakfast-cereals', 'Breakfast Cereals'),
    STRUCT('biscuits', 'Biscuits & Cookies'),
    STRUCT('cookies', 'Biscuits & Cookies'),
    STRUCT('biscuits-and-cakes', 'Biscuits & Cookies'),
    STRUCT('chocolate-biscuits', 'Biscuits & Cookies'),
    STRUCT('filled-biscuits', 'Biscuits & Cookies'),
    STRUCT('sweet-biscuits', 'Biscuits & Cookies'),
    STRUCT('salty-snacks', 'Snacks'),
    STRUCT('sweet-snacks', 'Snacks'),
    STRUCT('chips-and-fries', 'Snacks'),
    STRUCT('crackers', 'Snacks'),
    STRUCT('appetizers', 'Snacks'),
    STRUCT('extruded-snacks', 'Snacks'),
    STRUCT('chocolates', 'Chocolate & Confectionery'),
    STRUCT('chocolate-bars', 'Chocolate & Confectionery'),
    STRUCT('candies', 'Chocolate & Confectionery'),
    STRUCT('sweets', 'Chocolate & Confectionery'),
    STRUCT('confectioneries', 'Chocolate & Confectionery'),
    STRUCT('chocolate-candies', 'Chocolate & Confectionery'),
    STRUCT('beverages', 'Beverages'),
    STRUCT('sodas', 'Beverages'),
    STRUCT('fruit-juices', 'Beverages'),
    STRUCT('flavoured-waters', 'Beverages'),
    STRUCT('sports-drinks', 'Beverages'),
    STRUCT('iced-teas', 'Beverages'),
    STRUCT('nectars', 'Beverages'),
    STRUCT('energy-drinks', 'Beverages'),
    STRUCT('carbonated-drinks', 'Beverages'),
    STRUCT('soft-drinks', 'Beverages'),
    STRUCT('fruit-based-beverages', 'Beverages'),
    STRUCT('breads', 'Breads & Bakery'),
    STRUCT('breakfast-pastries', 'Breads & Bakery'),
    STRUCT('pastries', 'Breads & Bakery'),
    STRUCT('bakery-products', 'Breads & Bakery'),
    STRUCT('sandwich-breads', 'Breads & Bakery'),
    STRUCT('toasts', 'Breads & Bakery'),
    STRUCT('cakes', 'Breads & Bakery'),
    STRUCT('sauces', 'Sauces & Dressings'),
    STRUCT('salad-dressings', 'Sauces & Dressings'),
    STRUCT('mayonnaises', 'Sauces & Dressings'),
    STRUCT('ketchups', 'Sauces & Dressings'),
    STRUCT('mustards', 'Sauces & Dressings'),
    STRUCT('tomato-sauces', 'Sauces & Dressings'),
    STRUCT('spreads', 'Spreads & Jams'),
    STRUCT('sweet-spreads', 'Spreads & Jams'),
    STRUCT('chocolate-spreads', 'Spreads & Jams'),
    STRUCT('jams', 'Spreads & Jams'),
    STRUCT('hazelnut-spreads', 'Spreads & Jams'),
    STRUCT('nut-spreads', 'Spreads & Jams'),
    STRUCT('meals', 'Prepared Meals'),
    STRUCT('ready-meals', 'Prepared Meals'),
    STRUCT('prepared-meals', 'Prepared Meals'),
    STRUCT('frozen-meals', 'Prepared Meals'),
    STRUCT('frozen-foods', 'Prepared Meals'),
    STRUCT('processed-meats', 'Processed Meats'),
    STRUCT('sausages', 'Processed Meats'),
    STRUCT('charcuterie', 'Processed Meats'),
    STRUCT('prepared-meats', 'Processed Meats'),
    STRUCT('cooked-sausages', 'Processed Meats'),
    STRUCT('meat-analogues', 'Plant-Based Alternatives'),
    STRUCT('vegetable-based-products', 'Plant-Based Alternatives'),
    STRUCT('plant-based-meat-alternatives', 'Plant-Based Alternatives')
  ])
),
exploded AS (
  SELECT
    product_id,
    REPLACE(tag, 'en:', '') AS category
  FROM `YOUR_PROJECT.foodmythbuster.stg_products`,
    UNNEST(categories_tags) AS tag
  WHERE is_deceptive
)
SELECT
  m.grp AS category_group,
  COUNT(DISTINCT e.product_id) AS products
FROM exploded e
JOIN mapping m ON e.category = m.tag
GROUP BY m.grp
ORDER BY products DESC
